<a href="https://colab.research.google.com/github/Praveenpadidapu/Assignment-1-/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.

In [9]:
import numpy as np
data1=np.array([1,2,3,4,5])
data2=np.array([6,7,8,9,10])
print("first data",data1)
print("secound data",data2)
#addition of two arrays
print("addition of two given data",(data1+data2))
#subtraction of two arrays
print("subctraction of two given arrays",(data1-data2))
#multiplication of two arrays
print("multiplication of two given arrays",(data1*data2))
#modules of two arrays
print("modules of two  given arrays",(data1%data2))
#addition between two index
print("addition between two index",(data1[1]+data2[2]))
#multiplication between two index
print("multiplication between two index",(data2[2]*data2[3]))

first data [1 2 3 4 5]
secound data [ 6  7  8  9 10]
addition of two given data [ 7  9 11 13 15]
subctraction of two given arrays [-5 -5 -5 -5 -5]
multiplication of two given arrays [ 6 14 24 36 50]
modules of two  given arrays [1 2 3 4 5]
addition between two index 10
multiplication between two index 72


Write a script to compute the mean and standard deviation of a NumPy array.

In [15]:
import numpy as np
data=np.array([23,45,32,12,47])
# mean
print("mean of given data :",data.mean())
#standard deviation
data1=np.array([89,65,0,32,54,21])
print("standard deviation of given data",np.std(data1))


mean of given data : 31.8
standard deviation of given data 29.364093720052047


 Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [19]:
import numpy as np
data=np.arange(10,50,5)
print("numbers between 10 and 50 with difference 5 :",data)
print("resize of numbers as ",data.reshape(4,2))
print("resize of numbers as another form",data.reshape(2,4))

numbers between 10 and 50 with difference 5 : [10 15 20 25 30 35 40 45]
resize of numbers as  [[10 15]
 [20 25]
 [30 35]
 [40 45]]
resize of numbers as another form [[10 15 20 25]
 [30 35 40 45]]


Reshape the array into a 2x4 matrix.

In [20]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8])
print("elements of array :",data)
print("original shape of array :",data.shape)
print("Reshape the array into a 2x4 matrix.",data.reshape(2,4))


elements of array : [1 2 3 4 5 6 7 8]
original shape of array : (8,)
Reshape the array into a 2x4 matrix. [[1 2 3 4]
 [5 6 7 8]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.

In [23]:
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array :",data)
#Extract the sub-matrix containing the last two rows and first two columns.
print("sub-matrix containing the last two rows and first two columns ",data[-2:, :2])

original array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
sub-matrix containing the last two rows and first two columns  [[4 5]
 [7 8]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
 Replace all elements greater than 4 with 0.

In [27]:
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array :",data)
four=np.where(data>4,0,data)
print("replacing all elements with zero where grester than 4 :",four)
data[data>4]=0
print("another method")
print(data)


original array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
replacing all elements with zero where grester than 4 : [[1 2 3]
 [4 0 0]
 [0 0 0]]
another method
[[1 2 3]
 [4 0 0]
 [0 0 0]]


 Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [30]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("element wise addition,subtrction,division")
add=a+b
print("addition ",add)
mul=a*b
print("multiplication ",mul)
div=a/b
print("division ",div)


element wise addition,subtrction,division
addition  [5 7 9]
multiplication  [ 4 10 18]
division  [0.25 0.4  0.5 ]


Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.

In [38]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("overal mean ",data.mean())
column=np.mean(data,axis=0)
print("column wise ",column)
row=np.mean(data,axis=1)
print("row wise ",row)

[[0.38133595 0.80769919 0.70492256 0.91481684]
 [0.78036427 0.95384162 0.96041825 0.82399724]
 [0.07474653 0.51396492 0.31886232 0.16321954]
 [0.64233865 0.40813084 0.65095668 0.28585475]]
overal mean  0.5865918851900698
column wise  [0.46969635 0.67090914 0.65878995 0.54697209]
row wise  [0.70219364 0.87965534 0.26769833 0.49682023]



Create a random NumPy array of size (4, 4).
Maximum value of the entire array.
> Add blockquote



In [40]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("maximum of all array is :",data.max())

[[0.98156936 0.70493066 0.11721196 0.57906422]
 [0.88597596 0.21800345 0.60116152 0.64946315]
 [0.14173208 0.59039125 0.95432165 0.32307288]
 [0.01240549 0.4630181  0.1660377  0.81797543]]
maximum of all array is : 0.9815693596692999


Create a random NumPy array of size (4, 4)
Sum of all elements.

In [42]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("sum of all data in arrays :",np.sum(data))

[[0.87122375 0.2119001  0.56986248 0.48431341]
 [0.57856546 0.83475518 0.48518933 0.40340528]
 [0.98856415 0.80508598 0.98971166 0.05038438]
 [0.4000407  0.39604169 0.12462442 0.79177296]]
sum of all data in arrays : 8.985440919196815


 Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [46]:
import numpy as np
data=np.array([1,2,3,4])
for i in np.nditer(data):
  j=i+10
  k=j*2
  print(k)

22
24
26
28
