<a href="https://colab.research.google.com/github/Praveenpadidapu/Assignment-1-/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform arithmetic operations on NumPy arrays.

In [9]:
import numpy as np
data1=np.array([1,2,3,4,5])
data2=np.array([6,7,8,9,10])
print("first data",data1)
print("secound data",data2)
#addition of two arrays
print("addition of two given data",(data1+data2))
#subtraction of two arrays
print("subctraction of two given arrays",(data1-data2))
#multiplication of two arrays
print("multiplication of two given arrays",(data1*data2))
#modules of two arrays
print("modules of two  given arrays",(data1%data2))
#addition between two index
print("addition between two index",(data1[1]+data2[2]))
#multiplication between two index
print("multiplication between two index",(data2[2]*data2[3]))

first data [1 2 3 4 5]
secound data [ 6  7  8  9 10]
addition of two given data [ 7  9 11 13 15]
subctraction of two given arrays [-5 -5 -5 -5 -5]
multiplication of two given arrays [ 6 14 24 36 50]
modules of two  given arrays [1 2 3 4 5]
addition between two index 10
multiplication between two index 72


Write a script to compute the mean and standard deviation of a NumPy array.

In [15]:
import numpy as np
data=np.array([23,45,32,12,47])
# mean
print("mean of given data :",data.mean())
#standard deviation
data1=np.array([89,65,0,32,54,21])
print("standard deviation of given data",np.std(data1))


mean of given data : 31.8
standard deviation of given data 29.364093720052047


 Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [19]:
import numpy as np
data=np.arange(10,50,5)
print("numbers between 10 and 50 with difference 5 :",data)
print("resize of numbers as ",data.reshape(4,2))
print("resize of numbers as another form",data.reshape(2,4))

numbers between 10 and 50 with difference 5 : [10 15 20 25 30 35 40 45]
resize of numbers as  [[10 15]
 [20 25]
 [30 35]
 [40 45]]
resize of numbers as another form [[10 15 20 25]
 [30 35 40 45]]


Reshape the array into a 2x4 matrix.

In [20]:
import numpy as np
data=np.array([1,2,3,4,5,6,7,8])
print("elements of array :",data)
print("original shape of array :",data.shape)
print("Reshape the array into a 2x4 matrix.",data.reshape(2,4))


elements of array : [1 2 3 4 5 6 7 8]
original shape of array : (8,)
Reshape the array into a 2x4 matrix. [[1 2 3 4]
 [5 6 7 8]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.

In [23]:
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array :",data)
#Extract the sub-matrix containing the last two rows and first two columns.
print("sub-matrix containing the last two rows and first two columns ",data[-2:, :2])

original array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
sub-matrix containing the last two rows and first two columns  [[4 5]
 [7 8]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
 Replace all elements greater than 4 with 0.

In [27]:
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array :",data)
four=np.where(data>4,0,data)
print("replacing all elements with zero where grester than 4 :",four)
data[data>4]=0
print("another method")
print(data)


original array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
replacing all elements with zero where grester than 4 : [[1 2 3]
 [4 0 0]
 [0 0 0]]
another method
[[1 2 3]
 [4 0 0]
 [0 0 0]]


 Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [30]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("element wise addition,subtrction,division")
add=a+b
print("addition ",add)
mul=a*b
print("multiplication ",mul)
div=a/b
print("division ",div)


element wise addition,subtrction,division
addition  [5 7 9]
multiplication  [ 4 10 18]
division  [0.25 0.4  0.5 ]


Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.

In [38]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("overal mean ",data.mean())
column=np.mean(data,axis=0)
print("column wise ",column)
row=np.mean(data,axis=1)
print("row wise ",row)

[[0.38133595 0.80769919 0.70492256 0.91481684]
 [0.78036427 0.95384162 0.96041825 0.82399724]
 [0.07474653 0.51396492 0.31886232 0.16321954]
 [0.64233865 0.40813084 0.65095668 0.28585475]]
overal mean  0.5865918851900698
column wise  [0.46969635 0.67090914 0.65878995 0.54697209]
row wise  [0.70219364 0.87965534 0.26769833 0.49682023]



Create a random NumPy array of size (4, 4).
Maximum value of the entire array.
> Add blockquote



In [40]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("maximum of all array is :",data.max())

[[0.98156936 0.70493066 0.11721196 0.57906422]
 [0.88597596 0.21800345 0.60116152 0.64946315]
 [0.14173208 0.59039125 0.95432165 0.32307288]
 [0.01240549 0.4630181  0.1660377  0.81797543]]
maximum of all array is : 0.9815693596692999


Create a random NumPy array of size (4, 4)
Sum of all elements.

In [42]:
import numpy as np
data=np.random.rand(4,4)
print(data)
print("sum of all data in arrays :",np.sum(data))

[[0.87122375 0.2119001  0.56986248 0.48431341]
 [0.57856546 0.83475518 0.48518933 0.40340528]
 [0.98856415 0.80508598 0.98971166 0.05038438]
 [0.4000407  0.39604169 0.12462442 0.79177296]]
sum of all data in arrays : 8.985440919196815


 Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [46]:
import numpy as np
data=np.array([1,2,3,4])
for i in np.nditer(data):
  j=i+10
  k=j*2
  print(k)

22
24
26
28


Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100.
• Extract the first two rows and the last three columns from each "layer."


In [52]:
import numpy as np
data=np.random.randint(1,101,size=(3,4,5))
print(data)
extract=data[:2,-3:]
print("the first two rows and the last three columns ",extract)

[[[ 96  59  68  90  52]
  [ 48  83 100  34  78]
  [ 27  31   7  35   1]
  [ 63  56  38  46  13]]

 [[ 90  24  47  88  98]
  [ 58  72  27  44  75]
  [ 73   8  31  84  94]
  [ 24  58  50  70  28]]

 [[ 19  29  97  10  27]
  [  3   2  16  87  32]
  [ 17  38  50  28  12]
  [ 45  86  29  97  71]]]
the first two rows and the last three columns  [[[ 48  83 100  34  78]
  [ 27  31   7  35   1]
  [ 63  56  38  46  13]]

 [[ 58  72  27  44  75]
  [ 73   8  31  84  94]
  [ 24  58  50  70  28]]]


Replace all elements divisible by 3 with -1.

In [53]:
import numpy as np
data=np.random.randint(1,101,size=(3,4,5))
print(data)

three=np.where(data%3==0,-1,data)
print("repalcing with -1 :",three)

[[[ 94  80  84  73  87]
  [ 31  75 100  37  99]
  [ 80  45  94   7   3]
  [ 40  76  42  36  50]]

 [[  7  31  41  16  50]
  [  6  56  74  12  73]
  [ 47   9  28  64  74]
  [  9  66  10 100  75]]

 [[  8  14  32  62  80]
  [ 63  17  61  79  58]
  [ 50  97  79 100   6]
  [  8  67  72   8   8]]]
repalcing with -1 : [[[ 94  80  -1  73  -1]
  [ 31  -1 100  37  -1]
  [ 80  -1  94   7  -1]
  [ 40  76  -1  -1  50]]

 [[  7  31  41  16  50]
  [ -1  56  74  -1  73]
  [ 47  -1  28  64  74]
  [ -1  -1  10 100  -1]]

 [[  8  14  32  62  80]
  [ -1  17  61  79  58]
  [ 50  97  79 100  -1]
  [  8  67  -1   8   8]]]


Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100
Extract the second "layer" (i.e., the second 2D array) in the first dimension.

In [55]:
import numpy as np
data=np.random.randint(1,101,size=(3,4,5))
print(data)
secound=data[1,:,:]
print("secound array :",secound)

[[[  9   8  34  24  49]
  [ 44  55  48  48  41]
  [ 57  46  45  49  76]
  [ 27  61  92  74  41]]

 [[ 94   6  29  10  48]
  [ 95  46  73   8  93]
  [ 95  48  19  26  13]
  [ 13  44  31  98  59]]

 [[ 11  37  60  34  49]
  [ 20  70  60  99  83]
  [100  23   4  34  17]
  [ 80  23  75  45  51]]]
secound array : [[94  6 29 10 48]
 [95 46 73  8 93]
 [95 48 19 26 13]
 [13 44 31 98 59]]


Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).

In [59]:
import numpy as np
data=np.random.randint(1,21,size=(3,3))
print(data)
row_mean=np.mean(data,axis=1)
print("row vise: ",row)
subtract=data-row_mean
print("Subtract the mean of each row from its respective elements :",subtract)

[[ 8 12 18]
 [ 2 11  6]
 [ 3 16  4]]
row vise:  [11.33333333  8.         13.66666667]
Subtract the mean of each row from its respective elements : [[ -4.66666667   5.66666667  10.33333333]
 [-10.66666667   4.66666667  -1.66666667]
 [ -9.66666667   9.66666667  -3.66666667]]


Create a NumPy array arr of shape (3, 3) with random integers between
1 and 20.
 Create a new array by squaring all the elements in arr.

In [60]:
import numpy as np
data=np.random.randint(1,21,size=(3,3))
print(data)
square_array=data**2
print("square array is:",square_array)

[[17  7 13]
 [15  5  7]
 [ 5 17 20]]
square array is: [[289  49 169]
 [225  25  49]
 [ 25 289 400]]


Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20
Find the indices of the top 3 maximum values in the entire array.

In [63]:
import numpy as np
data=np.random.randint(1,21,size=(3,3))
print("array : ",data)
top_three=np.argpartition(data,-3)[-3:]
print(" indices of the top 3 maximum values :",top_three)

array :  [[ 5  4  4]
 [16  8 16]
 [13 10  4]]
 indices of the top 3 maximum values : [[1 0 2]
 [1 0 2]
 [2 1 0]]
